### PR TITLE
Update travis and fix badges

### PR DESCRIPTION
**Pull request by abinoam**

### CODE REVIEW

**Review by doomspork — APPROVED** [review]
Thanks @abinoam!  @mmozuras this will require a release from you

**Comment by abinoam** [comment]
Hi @doomspork I can see that some other pronto integrations also need to update their bags. I'm asking some beginners at our local Ruby group to take this opportunity to make their first pull request with the help of the more experienced. As it doesn't involve any code/tests, I see this as a great opportunity to begin (and throw away any fear of issueing PRs).

**Comment by doomspork** [comment]
@abinoam that is a _wonderful_ idea and I fully support this!  Please encourage others do as you have, this would be great for open source.

**Comment by mmozuras** [comment]
@abinoam love it! 👍

**Pull request merged**
